---
# tasks file for polycom-vvx-voipms-config


- name: making phone config
  template:
    src: generic-phone.cfg.j2
    dest: "{{ destination_path | default('/tftpboot') }}/{{ inventory_hostname }}-phone.cfg"
  delegate_to: "{{ provisioning_server }}"

...
